name: Packer Build

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-ami:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Packer AMI Build
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: create .env file from secrets
        run: |
          echo "ENV=${{ secrets.ENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_NAME_TEST=${{ secrets.DB_NAME_TEST }}" >> .env
          echo "TABLE_NAME=${{ secrets.TABLE_NAME }}" >> .env
          echo "GROUP_NAME=${{ secrets.GROUP_NAME }}" >> .env
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> .env
          echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> .env
          echo "APP_DIR=${{ secrets.APP_DIR }}" >> .env
          echo "ZIP_FILE=${{ secrets.ZIP_FILE }}" >> .env
    
      - name: Create dev.pkvars.hcl
        working-directory: packer
        run: |
          echo "aws_region       = \"${{ env.AWS_REGION }}\"" > packer/dev.pkvars.hcl
          echo "aws_instance_type = \"${{ env.AWS_INSTANCE_TYPE }}\"" >> dev.pkvars.hcl
          echo "aws_access_key   = \"${{ env.AWS_ACCESS_KEY }}\"" >> dev.pkvars.hcl
          echo "aws_secret_key   = \"${{ env.AWS_SECRET_KEY }}\"" >> dev.pkvars.hcl
          echo "source_ami       = \"${{ env.SOURCE_AMI }}\"" >> dev.pkvars.hcl
          echo "ami_name_prefix  = \"${{ env.AMI_NAME_PREFIX }}\"" >> dev.pkvars.hcl
          echo "db_name          = \"${{ env.DB_NAME }}\"" >> dev.pkvars.hcl
          echo "db_user          = \"${{ env.DB_USERNAME }}\"" >> dev.pkvars.hcl
          echo "db_password      = \"${{ env.DB_PASSWORD }}\"" >> dev.pkvars.hcl
          echo "db_host          = \"${{ env.DB_HOST }}\"" >> dev.pkvars.hcl
          echo "dev_user         = \"${{ env.DEV_USER }}\"" >> dev.pkvars.hcl

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create webapp.zip from existing directory
        run: |
          sudo apt-get update -y
          sudo npm install
          sudo apt-get install -y unzip
          zip -r webapp.zip .env .
          cp -r webapp.zip packer
        shell: bash

      - name: Copy webapp.zip to packer directory
        run: cp webapp.zip ./packer/

      - name: Run packer init
        working-directory: ./packer
        id: init
        run: packer init webapp-image.pkr.hcl

      - name: Run packer validate
        working-directory: ./packer
        id: validate
        run: packer validate --var-file=dev.pkvars.hcl webapp-image.pkr.hcl

      - name: Build AMI
        working-directory: ./packer
        run: packer build --var-file=dev.pkvars.hcl webapp-image.pkr.hcl
