name: Packer Build
'on':
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-ami:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Packer AMI Build
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables for Tests
        run: |
          echo "DB_USERNAME=\"${{ secrets.DB_USER_ROOT }}\"" >> .env
          echo "DB_PASSWORD=\"${{ secrets.DB_ROOT_PASSWORD }}\"" >> .env
          echo "DB_HOST=\"${{ secrets.DB_HOST }}\"" >> .env
          echo "ENV=\"test\"" >> .env
          echo "DB_NAME_TEST=\"${{ secrets.DB_NAME_TEST }}\"" >> .env
          

      - name: Enable mysql service
        run: sudo systemctl start mysql

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install

      - name: Wait for MySQL to be Ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done
          
      - name: Initialize MySQL Database as Root
        run: >
          sudo mysql -u${{secrets.DB_USER_ROOT}} -p${{ secrets.DB_ROOT_PASSWORD }} <<EOF

          CREATE DATABASE IF NOT EXISTS \`${{secrets.DB_NAME_TEST}}\`;

          EOF

      - name: Run Tests
        run: |
          npm test
          sudo rm -f .env

      - name: Create dev.pkvars.hcl
        working-directory: packer
        run: |
          echo "aws_region       = \"${{ secrets.AWS_REGION }}\"" > dev.pkvars.hcl
          echo "aws_instance_type = \"${{ secrets.AWS_INSTANCE_TYPE }}\"" >> dev.pkvars.hcl
          echo "aws_access_key   = \"${{ secrets.AWS_ACCESS_KEY_DEV }}\"" >> dev.pkvars.hcl
          echo "aws_secret_key   = \"${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}\"" >> dev.pkvars.hcl
          echo "source_ami       = \"${{ secrets.SOURCE_AMI }}\"" >> dev.pkvars.hcl
          echo "ami_name_prefix  = \"${{ secrets.AMI_NAME_PREFIX }}\"" >> dev.pkvars.hcl
          echo "dev_user         = \"${{ secrets.DEV_USER }}\"" >> dev.pkvars.hcl          

      
      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.12.0' 


        

      - name: Configure AWS Credentials dev profile
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_DEV }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}'
          aws-region: '${{ secrets.AWS_REGION }}'
          profile: dev

      - name: Configure AWS Credentials demo profile
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_DEMO }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}'
          aws-region: '${{ secrets.AWS_REGION }}'
          profile: demo

      - name: Create webapp.zip from existing directory
        run: |
          sudo apt-get update -y
          sudo npm install
          sudo apt-get install -y unzip
          zip -r webapp.zip .
          cp -r webapp.zip packer
        shell: bash

      - name: Run packer init
        working-directory: ./packer
        id: init
        run: packer init .
        
      - name: Validate Packer template
        working-directory: ./packer
        run: |
          packer validate --var-file=dev.pkvars.hcl webapp-image.pkr.hcl


      - name: Get and Set latest AMI verssion
        run: |
         AMI_ID=$(aws ec2 describe-images \
          --profile demo \
          --filters "Name=name,Values=webapp-image-*" \
          --query "Images | sort_by(@, &CreationDate) | [-1].ImageId" \
          --output text)
          --profile demo
          echo $(AMI_ID)
      
      - name: Create a new version of Launch template
        run: |
          AMI_ID=$(aws ec2 describe-images \
            --profile demo \
            --filters "Name=name,Values=webapp-image-*" \
            --query "Images | sort_by(@, &CreationDate) | [-1].ImageId" \
            --output text)

            echo $(AMI_ID)
            
          AWS_PAGER="" aws ec2 create-launch-template-version \
            --launch-template-id ${{ vars.DEMO_LAUNCH_TEMPLATE_ID }} \
            --source-version 1 \
            --launch-template-data '{"ImageId":"'"${AMI_ID}"'"}' \
            --profile demo \
            --no-paginate \
            --output json

      
      - name: Perform Instance refresh
        run: |
          aws autoscaling start-instance-refresh \
            --profile demo \
            --auto-scaling-group-name ${{ vars.DEMO_AUTO_SCALING_GROUP_NAME }} \
            --preferences MinHealthyPercentage=90 \
            --desired-configuration '{"LaunchTemplate": {"LaunchTemplateId": "${{ vars.DEMO_LAUNCH_TEMPLATE_ID }}", "Version": "$Latest"}}'






