name: pr-check-tests

on:
    pull_request:
      types: [ opened, reopened ]
      branches: [ "main" ]

jobs:
  setup-mysql-and-performing-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server=8.0.41* -y
          sudo systemctl start mysql

      - name: Configure MySQL
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "DB_NAME is '$DB_NAME'"
          sudo mysql -e "ALTER USER '${DB_USERNAME}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_PASSWORD}';"
          DB_EXISTS=$(mysql -u"$DB_USERNAME" -p"$DB_PASSWORD" -e "SHOW DATABASES LIKE '$DB_NAME';" | grep "$DB_NAME" > /dev/null; echo $?)
          if [ $DB_EXISTS -eq 0 ]; then
            echo "Database '$DB_NAME' already exists. Skipping creation."
          else
            echo "Database '$DB_NAME' does not exist. Creating database..."
            mysql -u"$DB_USERNAME" -p"$DB_PASSWORD" -e "CREATE DATABASE $DB_NAME;"
            echo "Database '$DB_NAME' created successfully."
          fi
