name: pr-check-tests

on:
    pull_request:
      types: [ opened, reopened ]
      branches: [ "main" ]

jobs:
  setup-mysql-and-performing-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server=8.0.41* -y
          sudo systemctl start mysql

      - name: Configure MySQL
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "DB_NAME is: " '$DB_USERNAME'
          sudo mysql -e "ALTER USER '${DB_USERNAME}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_PASSWORD}';"
          